name: Build Docs

on:
  push:
    branches: [main]

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install sphinx sphinx-rtd-theme myst-parser
        
    - name: Debug directory structure before build
      run: |
        echo "Current directory structure:"
        ls -R

      - name: Build docs
        run: |
          cd docs
          make html
      - name: Debug build output
        run: |
          echo "Docs build directory contents:"
          ls -R docs/build
      
      - name: Deploy to GH pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html